config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :index] do
    resources :goals, only: [:new]
  end
  resources :notifications, only: [:index]
  resource :account, only: [:edit, :update] do
    resources :sessions, only: [:index]
  end
  get "register", to: "users#new"
  get "login", to: "sessions#new"

  resources :sessions, only: [:create, :destroy]
  resources :goals, only: [:show, :index, :create, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :up_votes, only: [:create, :destroy]
  resources :notifications, only: [:update]  
end

app/models/user.rb
class User < ApplicationRecord
   include Commentable
   validates :username, presence: true, uniqueness: true
   validates :password_digest, presence: true
   validates :password, length: { minimum: 5, allow_nil: true } 
   validates_numericality_of( 
      :up_votes_left, 
      only_integer: true, 
      greater_than_or_equal_to: 0,
      on: :create
   )

   after_initialize :ensure_session_token
   before_validation :ensure_up_votes_left

   attr_reader :password

   has_many :goals, -> { order "created_at DESC"}, dependent: :destroy
   has_many :completed_goals, -> { where status: "Complete" }, class_name: "Goal"
   
   has_many :sessions, -> { order "created_at DESC"}, dependent: :destroy   
   
   has_many :up_votes, dependent: :destroy   
   has_many :up_voted_goals, through: :up_votes, source: :goal
   has_many :received_up_votes, through: :goals, source: :up_votes
   has_many( :authored_comments, 
      class_name: "Comment",
      foreign_key: :author_id,
      primary_key: :id,
      dependent: :destroy
  )
  has_many :notifications, -> { order "created_at DESC" }, dependent: :destroy
  has_many(
     :triggered_events, 
     class_name: "KeyEvent", 
     foreign_key: :instigator_id, 
     dependent: :destroy
   )

   scope :with_goals_count, -> do
      select("users.*, COUNT(DISTINCT goals.id) AS \"goals_count\"")
      .left_outer_joins(:goals)
      .group(:id)
   end
   scope :with_upvotes_count, -> do
      select("users.*, COUNT(DISTINCT up_votes.id) AS \"upvotes_count\"")
      .left_outer_joins(:received_up_votes)
      .group(:id)
   end
   scope :sorted_alphabetically, -> { order(:username) }

   def self.generate_session_token
      SecureRandom::urlsafe_base64(16)
   end

   def self.find_by_credentials(username, password)
      user = self.find_by(username: username)
      return user if user && user.is_password?(password)
      nil
   end

   def self.leaderboard
      self.find_by_sql(<<-SQL) 
      SELECT   
         users.*, COUNT(goals.id) AS goal_count, SUM ( 
            CASE WHEN goals.status = 'Complete'
            THEN 1
            ELSE 0
            END
         ) AS completed_goal_count, COALESCE( 100 * SUM (
            CASE WHEN goals.status = 'Complete'
            THEN 1
            ELSE 0
            END
         ) / NULLIF(COUNT(goals.id), 0), 0) AS goal_completion_rate
      FROM
         users
      LEFT OUTER JOIN
         goals ON goals.user_id = users.id
      GROUP BY
         users.id
      ORDER BY
         completed_goal_count DESC
      LIMIT 
         10
      SQL
   end   

   def is_password?(password)
      BCrypt::Password.new(self.password_digest) == password
   end

   def password=(password)
      @password = password
      self.password_digest = BCrypt::Password.create(password)
   end

   def reset_session_token!
      self.session_token = self.class.generate_session_token
      self.save!
      self.session_token
   end

   def increment_up_votes_left!
      self.up_votes_left += 1
      self.save!
      self.up_votes_left
   end

   def decrement_up_votes_left!
      self.up_votes_left -= 1
      self.save!
      self.up_votes_left
   end

   def has_up_votes_remaining?
      self.up_votes_left > 0
   end

   private
   def ensure_session_token
      self.session_token ||= self.class.generate_session_token
   end

   def ensure_up_votes_left
      self.up_votes_left ||= UpVote::UP_VOTE_LIMIT
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   skip_before_action :ensure_login, except: [:show]
   before_action :already_logged_in, only: [:create, :new]
   
   def new
      @user = User.new
   end

   def create
      @user = User.new(user_params)
      if @user.save
         login_user!(@user)
         redirect_to root_url
      else
         flash.now[:errors] = @user.errors.full_messages
         render :new
      end
   end

   def show
      @user = User.find_by_id(params[:id])
      if @user
         render :show
      else
         redirect_to users_url
      end
   end

   def index
      @users = User.all
      .with_goals_count
      .with_upvotes_count
      .sorted_alphabetically
   end

   private
   def user_params
      params.require(:user).permit(:username, :password)
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<form 
   action="<%= mode == :new_user ? users_url : sessions_url %>" 
   method="post"
   class="user"
   >
   <%= auth_token %>
   <label for="user_username">Username:
      <input 
      id="user_username" 
      type="text" 
      name="user[username]"
      <%= "placeholder=goal_champ" if mode == :new_user %>>
   </label>
   <label for="user_password">Password:
      <input 
      id="user_password" 
      type="password" 
      name="user[password]"
      <%= "placeholder=forgetMeNot568" if mode == :new_user %>>
   </label>
   <input type="submit" value="<%= mode == :new_user ? "Sign Up!" : "Sign In" %>">
</form>

app/views/users/index.html.erb
<header class="user-index r-panel top">
<h1>User Directory</h1>
<p>Browse by Username:</p>
<ul class="letter-links">
   <% letters = ("a".."z").to_a.select do |char| 
         !@users.where("LOWER(username) LIKE ?", "#{char}%").empty?
      end %>
   <% letters.each do |letter| %>
      <li>
         <%= link_to letter.upcase,"##{letter}" %>
      </li>
   <% end %>
</ul>
</header>
<% letters.each do |letter| %>
<section id="<%= letter %>" class="users-by-letter">
   <h3 class="index-letter"><%= letter.upcase %></h3>
   <%= link_to "Back to Top", "#", class: "back-to-top" %>
   <ol class="user-list">
   <% @users.where("LOWER(username) LIKE ?", "#{letter}%").each do |user| %>
      <li>
         <a class="container-link" href="<%= user_url(user) %>">
         <ol class="user-record">
            <li><strong><%= user.username %></strong></li>
            <li>has <data value="<%= user.goals_count %>"><%= user.goals_count %>
            </data> goal<%= "s" unless user.goals_count == 1 %>,</li>
            <li><data value="<%= user.upvotes_count %>"><%= user.upvotes_count %>
            </data> total upvote<%= "s" unless user.upvotes_count == 1 %></li>
            <li>and joined <time datetime="<%= 
            user.created_at.strftime("%Y-%m-%dT%H:%M") %>"%><!--
            --><%= user.created_at.strftime("%B %Y") %></time></li>
         </ol>
      </li>
   <% end %>
   </ol>
</section>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Here!</h1>
<section class="register user-form r-panel middle">
<%= render "shared/notices", notices: flash.now[:errors], type: "errors" %>
<%= render "users/form", mode: :new_user %>
</section>

app/views/users/show.html.erb
<% is_current_user = (current_user == @user) ? true : false %>
<% curr_user_headings = ["Goal", "Status", "Public?", "Upvotes", "Created", "Details"] %>
<% other_user_headings = ["Goal", "Status", "Upvotes", "Created", "Details"] %>
<section class="user-header l-panel top">
   <% if is_current_user %>
   <h1>Your Goals</h1>
   <p>
      <%= link_to ("Add a new goal " + 
            ApplicationHelper::ACTION_ICONS["new_goal"]).html_safe, 
            new_user_goal_url(current_user), 
            class: "new-goal" %>
   </p>
   <% else %>
   <h1><%= @user.username %>'s Goals</h1>
   <p><%= link_to "jump to comments", user_url(@user)+"#comments" %></p>
   <% end %>
</section>

<%= render "shared/notices", notices: flash[:success], type: "success" %>
<% goals = is_current_user ? @user.goals.with_up_votes_count.with_comments_count :
   @user.goals.with_up_votes_count.with_comments_count.set_public %>
<%= render  "goals/user_show_goals", 
      goals: goals,
      is_current_user: is_current_user %>

<%= render "comments/comments", target: @user %>