config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :index] do
    resources :goals, only: [:new]
  end
  resources :notifications, only: [:index]
  resource :account, only: [:edit, :update] do
    resources :sessions, only: [:index]
  end
  get "register", to: "users#new"
  get "login", to: "sessions#new"

  resources :sessions, only: [:create, :destroy]
  resources :goals, only: [:show, :index, :create, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :up_votes, only: [:create, :destroy]
  resources :notifications, only: [:update]  
end

app/views/shared/_notices.html.erb
<% if notices %>
   <ul class="<%= "notices #{type}" %>">
      <% notices.each do |notice| %>
         <li><%= notice %></li>
      <% end %>
   </ul>
<% end %>
   

app/views/shared/_site_footer.html.erb
<footer class="<%= is_logged_in? ? "site l-panel bottom" : "site r-panel bottom"%>">
  <nav class="site-nav">
    <div class="main-link-block">
      <h5 class="footer-link-heading">main</h5>
      <ul class="footer-link-list">
        <li><%= link_to "Home", root_url %></li>
        <li><%= link_to "Goal Index", root_url %></li>
        <li><%= link_to "User Index", root_url %></li>
      </ul>
    </div>
    <div class="user-link-block">
    <h5 class="footer-link-heading">user</h5>
      <ul class="footer-link-list">
        <% if is_logged_in? %>
        <li><%= link_to "Profile", user_url(current_user) %></li>
        <li><%= link_to "Account Settings", account_sessions_url %></li>
        <li><%= link_to "Notifications", notifications_url %></li>
        <% else %>
        <li><%= link_to "Register", register_url %></li>
        <li><%= link_to "Login", login_url %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <small>created by Josh Brown - &copy; 2020</small>
</footer>