config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :index] do
    resources :goals, only: [:new]
  end
  resources :notifications, only: [:index]
  resource :account, only: [:edit, :update] do
    resources :sessions, only: [:index]
  end
  get "register", to: "users#new"
  get "login", to: "sessions#new"

  resources :sessions, only: [:create, :destroy]
  resources :goals, only: [:show, :index, :create, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :up_votes, only: [:create, :destroy]
  resources :notifications, only: [:update]  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :ensure_login
  
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if is_logged_in? %>
<section class="start r-panel top">
   <h3>Let's get started!</h3>
   <ul>
      <li>
         Set a <%= link_to "new goal", new_user_goal_url(current_user) %>!
      </li>
      <li>
         View all <%= link_to "your goals", user_url(current_user) %> and comments on your profile.
      </li>
      <li>
         Keep an eye on the number of upvotes <%= ApplicationHelper::UP_VOTE_ICONS["up"].html_safe %> you have left to give out on the main toolbar.
      </li>
   </ul>
</section>
<% else %>
<header class="main-heading l-panel top">
   <h1>Resolute</h1>
   <p>The goal setting app!</p>
</header>
<section class="unrecognised_user">
   <div class="register">
      <h4>New here?</h4>
      <p>Register with us to set, update and track your own goals. Join our growing community and support each others' goals!</p>
      <%= button_to "Create an Account", register_url, method: :get %>
   </div>
   <div class="login">
      <h4>Old face?</h4>
      <p>Welcome back! You know the drill: log back into your account to continue tracking your goals.</p>
      <%= button_to "Log Back In", login_url, method: :get %>
   </div>
</section>
<% end %>

<!-- GOAL AND USER LEADERBOARDS -->
<section id="leaderboards" class="leaderboard">
   <h3>Leaderboards</h3>
   <figure class = "users-leader-table">
      <h4>Most Productive Users</h4>
      <% user_headings = ["Rank", "Username", "Goals", "Completion"] %>
      <table class="users-leaderboard">
         <thead>
            <% user_headings.each do |heading| %>
            <th>
               <%= heading %>
            </th>
            <% end %>
         </thead>
         <tbody>
            <% User.leaderboard.each_with_index do |user, i| %>
            <tr>
               <td><%= i+1 %></td>
               <td class=><%= link_to user.username, user_url(user) %></td>
               <td><%= user.goal_count %></td>
               <td><%= number_with_precision(
                  user.goal_completion_rate, 
                  precision: 2, 
                  strip_insignificant_zeros: true) %>%</td>
            </tr>
            <% end %>
         </tbody>
         <caption>Check out <%= link_to "all our users.", users_url %></caption>
      </table>
   </figure>
   <figure class = "goals-leader-table">
      <h4>Most Popular Goals</h4>
      <% goal_headings = ["Rank", "Title", "User", "Upvotes", "Status"] %>
      <table class="goals-leaderboard">
         <thead>
            <% goal_headings.each do |heading| %>
            <th <%= "class=mobile-hide" if heading == "User" %>>
               <%= heading %>
            </th>
            <% end %>
         </thead>
         <tbody>
            <% Goal.leaderboard.each_with_index do |goal, i| %>
            <tr>
               <td><%= i+1 %></td>
               <td><%= link_to goal.title, goal_url(goal) %></td>
               <td class="mobile-hide">
                  <%= link_to goal.user.username, user_url(goal.user) %>
               </td>
               <td><%= goal.up_votes_count %></td>
               <td><%= GoalsHelper::STATUS_ICONS[goal.status.downcase.gsub(" ", "-")].
               html_safe + "<span class=\"sr-only\">#{goal.status}</span>".
               html_safe %></td>
            </tr>
            <% end %>
         </tbody>
         <caption>Browse <%= link_to "all goals", goals_url %>.</caption>
      </table>
   </figure>
</section>