config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :index] do
    resources :goals, only: [:new]
  end
  resources :notifications, only: [:index]
  resource :account, only: [:edit, :update] do
    resources :sessions, only: [:index]
  end
  get "register", to: "users#new"
  get "login", to: "sessions#new"

  resources :sessions, only: [:create, :destroy]
  resources :goals, only: [:show, :index, :create, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :up_votes, only: [:create, :destroy]
  resources :notifications, only: [:update]  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resolute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c08ce6939b.js" crossorigin="anonymous">
    </script>
  </head>

  <body>
    <header class="site-header-bar">
      <nav class="clearfix">
        <h6 class="logo">
          <a href="<%= root_url %>">
            <i class="fas fa-check-square"></i> <!-- tick icon -->
            <!-- tag layout to prevent automatic spaces between letters -->
            <strong>r<em
            >e</em></strong
            ><strong>s<em
            >o</em></strong
            ><strong>l<em
            >u</em></strong
            ><strong>t<em
            >e</em></strong>
          </a>
        </h6>
        <ul class="main-links">
          <li><%= link_to "Browse Goals", goals_url %></li>
          <li><%= link_to "Browse Users", users_url %></li>
        </ul>
  
        <ul class="user-info">
          <% if is_logged_in? %>
          <li class="dash-upvotes">
            <%= ApplicationHelper::UP_VOTE_ICONS["up"].html_safe %>
            <strong class="upvotes-left"><%= current_user.up_votes_left %></strong>
          </li>
          <li class="notifications">
            <a href="#" class="notifications-hover">
              <i class="fas fa-bell notification-icon"></i>
            </a><!--
         --><% if notification_count %><!--
         --><strong class="notification-count"><!--
         --><%= notification_count %></strong><!--
          --><% end %><!--
         --><%= render "notifications/menu" if current_user.notifications %>
          </li>
          <li class="user-hover">
            
            <%= link_to current_user.username, user_url(current_user) %>
            <ul class="user-menu">
              <li class="menu-upvotes">
                <%= "#{current_user.up_votes_left} upvotes remaining" %>
              </li>
              <li>
                <%= link_to "Your Profile", user_url(current_user) %>
              </li>
              <li>
                  <%= link_to "Manage Account", account_sessions_url%>
              </li>
              <li>
                <%= link_to "Logout", session_url(current_session), method: :delete, class: "logout" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li class="new-user-links">
            <%= link_to "Register", register_url, method: :get, class: "sign-up"%>
          </li>
          <li class="new-user-links">
            <%= link_to "Login", login_url, method: :get, class: "login"%>
          </li>
          <% end %>
          <li class="hamburger">
            <a href="#" class="hamburger-hover">
              <svg viewBox="0 0 80 50" width="40" height="25">
                <rect width="80" height="11" rx="2"></rect>
                <rect y="19" width="80" height="11" rx="2"></rect>
                <rect y="38" width="80" height="11" rx="2"></rect>
              </svg>
            </a>
            <ul class="full-menu">
              <% if is_logged_in? %>
              <li class="menu-upvotes">
                <%= "#{current_user.up_votes_left} upvotes remaining" %>
              </li>
              <% end %>
              <li><%= link_to "Browse Goals", goals_url %></li>
              <li><%= link_to "Browse Users", users_url %></li>
              <% if is_logged_in? %>
              <li><%= link_to "Your Profile", user_url(current_user) %></li>
              <li>
                  <%= link_to "Manage Account", account_sessions_url%>
              </li>
              <li>
                <%= link_to "Logout", session_url(current_session), method: :delete, class: "logout" %>
              </li>
              <% else %>
              <li><%= link_to "Register", register_url, method: :get, class: "sign-up"%></li>
              <li><%= link_to "Login", login_url, method: :get, class: "login"%></li>
              <% end %>
            </ul>
          </li>
        </ul>      
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <%= render "shared/site_footer" %>
  </body>
</html>